ATO-171: Attach policy to give orchestration-redirect lambda read access to user profile dynamo tables
govuk-one-login/authentication-api pull request #3767
Opened 2024-01-09 15:34 UTC by billrdunn

## What?

Give orchestration-redirect lambda permission to read user profile dynamo tables.

## Why?

Fixes deployment error: `.../staging-orchestration-redirect-lambda is not authorized to perform: dynamodb:DescribeTable on resource: .../staging-user-profile`

## Related PRs

https://github.com/govuk-one-login/authentication-api/pull/3741 failed during deployment with the above error.

2024-01-09 15:45 UTC, gn-GDS approved these changes

2024-01-10 10:07 UTC, ethanmills approved these changes

2024-01-10 10:08 UTC, ethanmills requested changes
Could you move the new role to the bottom of the list please

2024-01-10 11:52 UTC, ethanmills approved these changes

2024-01-10 12:01 UTC, merged