add part phone number to user exists api
govuk-one-login/authentication-api pull request #3799
Opened 2024-01-12 15:40 UTC by mark-cab

## What?

Added the phoneNumberLastThree field to the CheckUserExists API response.

## Why?

Previously decided to user CheckUserExists API to present data for the new MFA PW reset journey as the user is not logged in before this journey so we require more information to proceed through the screens. This update adds the last 3 digits to API response so that the frontend can use it for the text 'We have sent a code to your phone number ending with XXX'.

2024-01-17 15:43 UTC, LazarAlexandru-Constantin requested changes

2024-01-17 15:43 UTC, LazarAlexandru-Constantin commented on integration-tests/src/test/java/uk/gov/di/authentication/api/CheckUserExistsIntegrationTest.java
> +        }
I suggest adding another if statement to check if the mfaMethodType is of type AUTH_APP. If so, then to check if the getPhoneNumberLastThree() returns an empty string.

2024-01-19 10:32 UTC, LazarAlexandru-Constantin approved these changes

2024-01-19 10:36 UTC, BeckaL approved these changes

2024-02-01 16:13 UTC, merged