AUT-3909: remove lambda provisioned from dev account
govuk-one-login/authentication-api pull request #5584
Opened 2024-11-26 14:37 UTC by pskushwaha1

## What

remove lambda provisioned from dev account 
we are incurring $2000 monthly for lambda concurrency in DEV account ( di-auth-development ) , concurrency is not required in non performance dev account 

## How to review

1. Code Review
1. Deploy to sandpit with `./deploy-sandpit.sh -a`
1. Ensure that resources `x`, `y` and `z` were not changed
1. Visit [some url](https://some.sandpit.url/to/visit)
1. Log in
1. Ensure `x` message appears in a modal
-->

2024-12-03 17:14 UTC, whi-tw requested changes
Other than the comments in the `.lock.hcl` files, this all looks good!

2024-12-03 17:14 UTC, whi-tw commented on ci/terraform/account-management/.terraform.lock.hcl
> +provider "registry.terraform.io/hashicorp/null" {
This seems incorrect, could you please drop this change?

2024-12-03 17:14 UTC, whi-tw commented on ci/terraform/test-services/.terraform.lock.hcl
> +provider "registry.terraform.io/hashicorp/null" {
as above:

> This seems incorrect, could you please drop this change?

2024-12-04 14:08 UTC, pskushwaha1 commented on ci/terraform/test-services/.terraform.lock.hcl
> +provider "registry.terraform.io/hashicorp/null" {
done removed the HCL changes

2024-12-04 14:51 UTC, whi-tw approved these changes
LGTM

2024-12-05 11:21 UTC, merged